### ISSUE TITLE
Pussyheal doesn't work

### ISSUE THREAD

**Issue by idogadol** [Shabakur/RJW_More_#1]
It just doesn't heal.

**Comment by Shabakur** [comment]
Could you give some more context? It works fine in my testing.

**Comment by idogadol** [comment]
Hi, thanks for replying, it's my bad, I misunderstood how the ability works.
I thought it heals over time so I set it to SexOverdrive which resulted in the pawn never getting healed, I see now that it heals like a Sanguphage's Coagulate when they orgasm.
