### ISSUE TITLE
Sexfrenzy overrides settings

### ISSUE THREAD

**Issue by idogadol** [Shabakur/RJW_More_#3]
Sexfrenzy makes pawns completely ignore the RJW settings.
I have bestiality and gay males disabled yet using sexfrenzy makes animals and humans rape each other, as well as makes men rape men, 
can you please make it so the ability obeys the RJW settings?

**Comment by Shabakur** [comment]
Just released a small update, this and the mindbreak lance should be fixed now

**Comment by idogadol** [comment]
Thank you!
